version: "3"
services:   
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/ssl:/etc/ssl
    # start sed
      - /app/id1-portal/attachments:/id1-portal/attachments
      - ./id1-portal/nginx.conf:/etc/nginx/id1-portal/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    restart: always
  prerender:
    image: tvanro/prerender-alpine
    container_name: prerender
    environment:
      - MEMORY_CACHE=0
      - CACHE_MAXSIZE=1000
      - CACHE_TTL=6000
    restart: unless-stopped
  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
networks:
  default:
    external:
      name: projects_network
