FROM node:12-alpine as build

EXPOSE 8080 8081 4000

ENV DB_HOST=postgres-db-id1-portal
#ENV DB_USER=ogp_user
#ENV DB_PASSWORD=.#}2bkhSj@PH
#ENV DB_NAME=ogp
ENV DB_USER=postgres
ENV DB_PASSWORD=Qd8q9StE
ENV DB_NAME=kru
ENV DB_PORT=5432
ENV NODE_ENV=production
ENV PORTAL_ID=1
ENV PORT=4000
ENV PLUGINS_PORT=4001
ENV MAX_POOL_SIZE=15
ENV MIN_POOL_SIZE=5
ENV DB_KEEP_ALIVE=1
ENV EMAIL_HOST=smtp.gmail.com
ENV EMAIL_PORT=587
ENV EMAIL_USER=test@gmail.com
ENV EMAIL_PASSWORD=.#}2bkhSj@PH
ENV ATTACHMENT_LOCAL_PATH=/attachments
ENV PRIVATE_ATTACHMENT_LOCAL_PATH=/private-attachments
ENV ATTACHMENT_URL=/attachments
ENV TECHNICAL_HOST_NAME=
ENV PUBLIC_HOST=http://kstest.department.org.ua
ENV ADMIN_HOST=http://admin.kstest.department.org.ua
ENV API_HOST=http://kstest.department.org.ua/api

ENV USER_EMAIL=shkolnyi.r@gmail.com
ENV USER_PASSWORD=Mjc5YTZkNW
ENV USER_NAME=root_admin

ENV SECRET_KEY_RECAPTCHA=6Ld-pvUcAAAAAMvb00UHWEymoeTg-oTl_YlNaU27
ENV CAPTCHA_KEY=6Ld-pvUcAAAAAGobsHZqyba37Z1LX9mWGh3KCT8y
ENV TZ=Europe/Kiev





COPY ./projects /app

# Building migradion
WORKDIR /app/db_migrate
RUN npm install && npm run compile 
# npm run migrate
# Building plugin-tools
WORKDIR /app/plugin-tools
RUN npm install -g
# Building backend
WORKDIR /app/backend
RUN npm i && npm run compile
# Building admin
WORKDIR /app/admin
RUN npm i && npm run build
# Building public
WORKDIR /app/public
RUN npm i && npm run build



FROM node:12-alpine as final

ENV DB_HOST=postgres-db-id1-portal
#ENV DB_USER=ogp_user
#ENV DB_PASSWORD=.#}2bkhSj@PH
#ENV DB_NAME=ogp
ENV DB_USER=postgres
ENV DB_PASSWORD=Qd8q9StE
ENV DB_NAME=kru
ENV DB_PORT=5432
ENV NODE_ENV=production
ENV PORTAL_ID=1
ENV PORT=4000
ENV PLUGINS_PORT=4001
ENV MAX_POOL_SIZE=15
ENV MIN_POOL_SIZE=5
ENV DB_KEEP_ALIVE=1
ENV EMAIL_HOST=smtp.gmail.com
ENV EMAIL_PORT=587
ENV EMAIL_USER=test@gmail.com
ENV EMAIL_PASSWORD=.#}2bkhSj@PH
ENV ATTACHMENT_LOCAL_PATH=/attachments
ENV PRIVATE_ATTACHMENT_LOCAL_PATH=/private-attachments
ENV ATTACHMENT_URL=/attachments
ENV TECHNICAL_HOST_NAME=
ENV PUBLIC_HOST=http://kstest.department.org.ua
ENV ADMIN_HOST=http://admin.kstest.department.org.ua
ENV API_HOST=http://kstest.department.org.ua/api

ENV USER_EMAIL=shkolnyi.r@gmail.com
ENV USER_PASSWORD=Mjc5YTZkNW
ENV USER_NAME=root_admin

ENV SECRET_KEY_RECAPTCHA=6Ld-pvUcAAAAAMvb00UHWEymoeTg-oTl_YlNaU27
ENV CAPTCHA_KEY=6Ld-pvUcAAAAAGobsHZqyba37Z1LX9mWGh3KCT8y
ENV TZ=Europe/Kiev


WORKDIR /app
# Installing server and PM2
RUN npm install serve -g && npm install pm2 -g && pm2 install pm2-logrotate

COPY --from=build /app/admin/build /app/admin/build
COPY --from=build /app/admin/package.json /app/admin/package.json
COPY --from=build /app/backend/dist /app/backend/dist
COPY --from=build /app/backend/src /app/backend/src
COPY --from=build /app/backend/node_modules /app/backend/node_modules
COPY --from=build /app/backend/package.json /app/backend/package.json
COPY --from=build /app/public/build /app/public/build
COPY --from=build /app/public/package.json /app/public/package.json
COPY --from=build /app/db_migrate/ /app/db_migrate/
#COPY --from=build /app/db_migrate/package.json /app/db_migrate/package.json
COPY --from=build /app/ecosystem.config.js /app/ecosystem.config.js

COPY ./attachments /attachments
COPY ./private-attachments /private-attachments
COPY ./logs/pm2/ /root/.pm2/logs/
COPY ./projects/pluginsInfo /app/pluginsInfo




ENTRYPOINT pm2 start ecosystem.config.js --no-daemon