version: "3"
services:
  postgres-db-id1-portal:
    image: postgres:11
    container_name: postgres-db-id1-portal
    environment:
      - POSTGRES_USER=ogp_user
      - POSTGRES_PASSWORD=.#}2bkhSj@PH
      - POSTGRES_DB=ogp
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
  pm2-projects:
    container_name: pm2-projects-id1-portal
    image: node:12-alpine
    environment:
      - NODE_ENV=production
      - PORTAL_ID=1
      - PORT=4000
      - PLUGINS_PORT=4001
      - DB_HOST=postgres-db-id1-portal
      - DB_USER=ogp_user
      - DB_PASSWORD=.#}2bkhSj@PH
      - DB_NAME=ogp
      - DB_PORT=5432
      - MAX_POOL_SIZE=15
      - MIN_POOL_SIZE=5
      - DB_KEEP_ALIVE=1
      - PRIVATE_KEY=Mjc5YTZkNWNjZDVhNGYwZTNmODBkYTlh
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USER=test@gmail.com
      - EMAIL_PASSWORD=.#}2bkhSj@PH

      - ATTACHMENT_LOCAL_PATH=/attachments
      - PRIVATE_ATTACHMENT_LOCAL_PATH=/private-attachments
      - ATTACHMENT_URL=/attachments

      - TECHNICAL_HOST_NAME=
      - PUBLIC_HOST=http://ogp.gov.ua:8080
      - ADMIN_HOST=http://admin.ogp.gov.ua:8081
      - API_HOST=http://ogp.gov.ua:4000

      - USER_EMAIL=shkolnyi.r@gmail.com
      - USER_PASSWORD=Mjc5YTZkNW
      - USER_NAME=root_admin

      - SECRET_KEY_RECAPTCHA=6Ld-pvUcAAAAAMvb00UHWEymoeTg-oTl_YlNaU27
      - CAPTCHA_KEY=6Ld-pvUcAAAAAGobsHZqyba37Z1LX9mWGh3KCT8y
      - TZ=Europe/Kiev
    volumes:
      - ./projects:/app
      - ./attachments:/attachments
      - ./private-attachments:/private-attachments
      - ./logs/pm2/:/root/.pm2/logs/
    ports:
      - 8080:8080
      - 8081:8081
      - 4000:4000
    working_dir: /app
    command:
      "sh -c 'cd db_migrate && npm install && npm run compile && npm run migrate && cd ..
      && cd plugin-tools && npm install -g && cd ..
      && cd backend && npm i && npm run compile && cd ..
      && cd admin && npm i && npm run build && cd ..
      && cd public && npm i && npm run build && cd ..
      && npm install serve -g && npm install pm2 -g && pm2 start ecosystem.config.js --no-daemon && pm2 install pm2-logrotate'"
    restart: always
networks:
  default:
    external:
      name: projects_network
